version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # Docker Compose autatically loads the .env file in current folder
      # Those values can be used only in this file
      # Those values won't be available in the container
      # We need to reset those in an environment block, or
      # Load them with env_file: \n \t ,env
      # Loading vars in that way will make then avaiable in the container
      # Pick just one to do it.
      - DISPLAY=${DISPLAY}
    user: vscode
    command: sleep infinity
