version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.gitconfig-custom-fernandobhz:/home/vscode/.gitconfig
    environment:
      - DISPLAY=${DISPLAY}
    user: vscode
    command: sleep infinity
